name: "Building and Pushing Docker Image"
on:
  workflow_dispatch:   # allows manual triggering from GitHub UI
  push:
    branches:
      - python-app-deployment
    paths:
      - '*.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - '/template/**'

env:
  TF_VAR_do_token: ${{ secrets.DO_CONNECT_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_CONNECT_TOKEN }}    # ensure this secret exists

      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/smoke/python-app:latest .
      
      - name: Login to DigitalOcean registry
        run: doctl registry login

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/smoke/python-app:latest